### ISSUE TITLE
Add localStorage to Alert

### ISSUE THREAD

**Issue by dssecret** [dssecret/dssecret.github.io#36]
Alert on all pages:
`function giveInfo() {
            if (window.confirm("By coming to this website, you are required to report any bugs at the Issue Tracker. Click OK to continue.")) {
            } else {
                window.location.href = "https://www.bing.com";
            }
        }`

**Comment by dssecret** [comment]
Commits 7b117bb, 29f3da8, and 402177 were actually for Issue #35

**Comment by DSSecret-Studios** [comment]
Mostly fixed with commit a0a6da3. Ben Game needs the `giveInfo` function.

**Comment by DSSecret-Studios** [comment]
Still not working on Cookie Clicker and possibly more!!!

**Comment by DSSecret-Studios** [comment]
Commit b7a7397 worked.

**Comment by DSSecret-Studios** [comment]
New code in commit b7a7397

**Comment by DSSecret-Studios** [comment]
Fully fixed with commits b7a7397 and f817fd7.
